# Generated by Django 4.2.5 on 2023-09-25 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('producer', models.CharField(max_length=50)),
                ('synopsis', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='images/')),
                ('trailer_url', models.CharField(max_length=50)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'G'), (2, 'PG'), (3, 'PG-13'), (4, 'R'), (5, 'NC-17')])),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Coming Soon'), (2, 'Currently Showing'), (3, 'No Longer Showing')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=10)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'User'), (2, 'Owner'), (3, 'Admin')], default=1)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (2, 'Suspended')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('card_number', models.PositiveBigIntegerField()),
                ('expiration_date', models.DateField()),
                ('cvv', models.PositiveSmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simply_cinema.user')),
            ],
        ),
    ]
