# Generated by Django 4.2.5 on 2023-09-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simply_cinema', '0002_remove_movie_image_movie_cast_movie_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Action'), (2, 'Comedy'), (3, 'Drama'), (4, 'Horror'), (5, 'Romance')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='review_score',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
