# Generated by Django 4.2.5 on 2023-09-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simply_cinema', '0003_movie_genre_movie_runtime_movie_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image_url',
            field=models.CharField(max_length=500),
        ),
    ]
