# Generated by Django 4.2.6 on 2023-10-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simply_cinema', '0008_alter_paymentcard_postal_code_alter_user_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcard',
            name='card_number',
            field=models.CharField(max_length=16),
        ),
    ]
