# Generated by Django 4.2.6 on 2023-10-30 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simply_cinema', '0009_alter_paymentcard_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcard',
            name='cvv',
            field=models.CharField(max_length=3),
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simply_cinema.user')),
            ],
        ),
    ]
