# Generated by Django 4.2.6 on 2023-10-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simply_cinema', '0010_alter_paymentcard_cvv_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forgot_password_code',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Verification',
        ),
    ]
