# Generated by Django 4.2.6 on 2023-12-02 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simply_cinema', '0013_alter_paymentcard_card_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentcard_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simply_cinema.paymentcard')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('rate', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('discount', models.PositiveSmallIntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_released', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simply_cinema.movie')),
                ('screen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simply_cinema.screen')),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.PositiveSmallIntegerField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simply_cinema.booking')),
                ('price_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simply_cinema.price')),
                ('showing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simply_cinema.showing')),
            ],
        ),
        migrations.AddField(
            model_name='screen',
            name='theater_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simply_cinema.theater'),
        ),
        migrations.AddField(
            model_name='booking',
            name='promotion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simply_cinema.promotion'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simply_cinema.user'),
        ),
    ]
