# Generated by Django 4.2.6 on 2023-12-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simply_cinema', '0014_booking_fee_price_promotion_screen_showing_theater_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.CharField(max_length=3),
        ),
    ]
