# Generated by Django 4.2.6 on 2023-12-08 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simply_cinema', '0015_alter_ticket_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='promotion_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simply_cinema.promotion'),
        ),
    ]
