# Generated by Django 4.2.6 on 2023-12-08 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simply_cinema', '0016_alter_booking_promotion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
