INSERT INTO simply_cinema_movie (title, year, runtime, genre, director, producer, cast, synopsis, review_score, image_url, trailer_url, rating, status)
VALUES 
    (
        'The Shawshank Redemption',
        1994,
        142,
        3,
        'Frank Darabont', 
        'Niki Marvin', 
        'Tim Robbins, Morgan Freeman, Bob Gunton', 
        'Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion.', 
        5, 
        'https://media-cache.cinematerial.com/p/500x/b5v2e9jg/the-shawshank-redemption-movie-poster.jpg', 
        'https://www.youtube.com/watch?v=PLl99DlL6b4', 
        4, 
        1
    ),
    (
        'The Godfather',
        1972,
        175,
        3,
        'Francis Ford Coppola',
        'Albert S. Ruddy',
        'Marlon Brando, Al Pacino, James Caan',
        'Don Vito Corleone, head of a mafia family, decides to hand over his empire to his youngest son Michael. However, his decision unintentionally puts the lives of his loved ones in grave danger.',
        5,
        'https://media-cache.cinematerial.com/p/500x/id2w2swk/the-godfather-movie-poster.jpg',
        'https://www.youtube.com/watch?v=1x0GpEZnwa8',
        4,
        1
    ),
    (
        'The Dark Knight',
        2008,
        152,
        1,
        'Christopher Nolan',
        'Emma Thomas, Charles Roven, Christopher Nolan',
        'Christian Bale, Heath Ledger, Aaron Eckhart',
        'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
        5,
        'https://media-cache.cinematerial.com/p/500x/udapnxr3/the-dark-knight-movie-poster.jpg',
        'https://www.youtube.com/watch?v=_PZpmTj1Q8Q',
        3,
        1
    ),
    (
        'The Big Short',
        2015,
        130,
        2,
        'Adam McKay',
        'Brad Pitt, Dede Gardner, Jeremy Kleiner, Arnon Milchan',
        'Christian Bale, Steve Carell, Ryan Gosling',
        'In 2006-2007 a group of investors bet against the United States mortgage market. In their research, they discover how flawed and corrupt the market is.',
        4,
        'https://media-cache.cinematerial.com/p/500x/2qaremyo/the-big-short-movie-poster.jpg',
        'https://www.youtube.com/watch?v=vgqG3ITMv1Q',
        4,
        1
    ),
    (
        'Suicide Squad',
        2016,
        123,
        1,
        'David Ayer',
        'Charles Roven, Richard Suckle',
        'Will Smith, Jared Leto, Margot Robbie',
        'A secret government agency recruits some of the most dangerous incarcerated super-villains to form a defensive task force. Their first mission: save the world from the apocalypse.',
        3,
        'https://media-cache.cinematerial.com/p/500x/ilrzmv7o/suicide-squad-movie-poster.jpg',
        'https://www.youtube.com/watch?v=CmRih_VtVAs',
        3,
        1
    ),
    (
        'Murder on the Orient Express',
        2017,
        114,
        3,
        'Kenneth Branagh',
        'Ridley Scott, Mark Gordon, Simon Kinberg, Kenneth Branagh, Judy Hofflund, Michael Schaefer',
        'Kenneth Branagh, Penelope Cruz, Willem Dafoe',
        'When a murder occurs on the train on which hes travelling, celebrated detective Hercule Poirot is recruited to solve the case.',
        3,
        'https://media-cache.cinematerial.com/p/500x/epjzqsvo/murder-on-the-orient-express-theatrical-movie-poster.jpg',
        'https://www.youtube.com/watch?v=Mq4m3yAoW8E',
        3,
        2
    ),
    (
        'The Meg',
        2018,
        113,
        1,
        'John Turteltaub',
        'Lorenzo di Bonaventura, Belle Avery, Colin Wilson',
        'Jason Statham, Bingbing Li, Rainn Wilson',
        'A group of scientists exploring the Marianas Trench encounter the largest marine predator that has ever existed - the Megalodon.',
        3,
        'https://media-cache.cinematerial.com/p/500x/1ctna1ur/the-meg-movie-poster.jpg',
        'https://www.youtube.com/watch?v=bsLk0NPRFAc',
        3,
        2
    ),
    (
        'Midsommar',
        2019,
        148,
        4,
        'Ari Aster',
        'Patrik Andersson, Lars Knudsen',
        'Florence Pugh, Jack Reynor, Vilhelm Blomgren',
        'A couple travels to Northern Europe to visit a rural hometowns fabled Swedish mid-summer festival. What begins as an idyllic retreat quickly devolves into an increasingly violent and bizarre competition at the hands of a pagan cult.',
        4,
        'https://media-cache.cinematerial.com/p/500x/aydewxpj/midsommar-movie-poster.jpg',
        'https://www.youtube.com/watch?v=1Vnghdsjmd0',
        4,
        2
    ),
    (
        'No Time to Die',
        2021,
        163,
        1,
        'Cary Joji Fukunaga',
        'Michael G. Wilson, Barbara Broccoli',
        'Daniel Craig, Ana de Armas, Rami Malek',
        'James Bond has left active service. His peace is short-lived when Felix Leiter, an old friend from the CIA, turns up asking for help, leading Bond onto the trail of a mysterious villain armed with dangerous new technology.',
        4,
        'https://media-cache.cinematerial.com/p/500x/xgeu917g/no-time-to-die-international-theatrical-movie-poster.jpg',
        'https://www.youtube.com/watch?v=vw2FOYjCz38',
        3,
        2
    ),
    (
        'Everything Everywhere All at Once',
        2022,
        139,
        3,
        'Daniel Kwan, Daniel Scheinert',
        'Anthony Russo, Joe Russo, Mike Larocca, Daniel Kwan, Daniel Scheinert, Jonathan Wang, Peter Tam Lee',
        'Mimi Keene, Josephine Langford, Hero Fiennes Tiffin',
        'After breaking up with his true love, best-selling author Hardin Scott travels to Portugal in an attempt to make amends for his past behavior.',
        4,
        'https://media-cache.cinematerial.com/p/500x/ckamivwa/everything-everywhere-all-at-once-movie-poster.jpg',
        'https://www.youtube.com/watch?v=wxN1T1uxQ2g',
        4,
        2
    );